name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodejs }}

      - name: (cache) restore
        uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: Install
        run: npm install

      - name: (coverage) Test
        run: npm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
